name: ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - run: go test -v ./...
      env:
        CGO_ENABLED: 0
        WORKFLOW_TEST_MOCKING: true
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      env:
        CGO_ENABLED: 0
      with:
        version: latest
